# core/maths_ai.py
from core.subjects.maths import PLANNING_PROMPT, GENERATION_PROMPT_ADDITION

class MathsSubject:
    PLANNING_PROMPT = PLANNING_PROMPT
    GENERATION_PROMPT_ADDITION = GENERATION_PROMPT_ADDITION
