# core/physics_ai.py
from core.subjects.physics import PLANNING_PROMPT, GENERATION_PROMPT_ADDITION

class PhysicsSubject:
    PLANNING_PROMPT = PLANNING_PROMPT
    GENERATION_PROMPT_ADDITION = GENERATION_PROMPT_ADDITION
