# core/physics_ai.py
"""
Physics AI Engine
Converts natural language experiment descriptions to Three.js + Cannon-es code.
Uses Gemini 3.0 Flash (with 2.5 Flash fallback).
"""

import json
import re
from core.engine import KusmusAIEngine
from core.key_manager import key_manager


# System prompt for physics experiments
PHYSICS_SYSTEM_PROMPT = """
You are a Physics Lab Assistant powered by Gemini 3.0 Flash (or Gemini 2.5 Flash as fallback) that converts natural language experiment descriptions into Three.js + Cannon-es visualization code.

Your task:
1. Parse the experiment description carefully
2. Identify physics objects (spheres, boxes, planes, pendulums, etc.)
3. Extract physics parameters (mass, velocity, gravity, friction, restitution, dimensions)
4. Generate valid, complete Three.js code that visualizes the experiment
5. Include realistic physics simulation using cannon-es

Output Format (JSON):
{
    "title": "Descriptive experiment title",
    "description": "Brief description of what will be visualized",
    "concept": "Physics concept being demonstrated",
    "threejs_code": "Complete, executable JavaScript code",
    "physics_config": {
        "gravity": [x, y, z],
        "timeScale": 1.0
    },
    "objects": [
        {
            "id": "unique_id",
            "name": "descriptive_name",
            "type": "sphere|box|plane|cylinder",
            "position": [x, y, z],
            "params": {"radius": 1, "width": 2, "height": 1},
            "physics": {
                "mass": 1,
                "velocity": [vx, vy, vz],
                "friction": 0.5,
                "restitution": 0.7
            },
            "adjustable": {
                "mass": {"min": 0.1, "max": 100, "step": 0.1},
                "velocity": {"min": -20, "max": 20, "step": 0.5}
            }
        }
    ],
    "parameters": {
        "gravity": {"min": 1, "max": 20, "value": 9.81},
        "timeScale": {"min": 0.1, "max": 5, "value": 1.0}
    },
    "estimated_runtime": 5000,
    "errors": []
}

Three.js + Cannon-es Code Template:
```javascript
// Physics Experiment Visualization
// Generated by PhysicsAI (Gemini 3.0 Flash)

(function() {
    // Scene setup
    const scene = new THREE.Scene();
    scene.background = new THREE.Color(0x1a1a2e);
    
    const camera = new THREE.PerspectiveCamera(60, window.innerWidth / window.innerHeight, 0.1, 1000);
    camera.position.set(10, 8, 15);
    camera.lookAt(0, 2, 0);
    
    const renderer = new THREE.WebGLRenderer({ antialias: true });
    renderer.setSize(window.innerWidth, window.innerHeight);
    renderer.shadowMap.enabled = true;
    document.body.appendChild(renderer.domElement);
    
    // Lighting
    const ambientLight = new THREE.AmbientLight(0x404040, 0.5);
    scene.add(ambientLight);
    
    const directionalLight = new THREE.DirectionalLight(0xffffff, 1);
    directionalLight.position.set(10, 20, 10);
    directionalLight.castShadow = true;
    scene.add(directionalLight);
    
    // Physics world (Cannon-es)
    const world = new CANNON.World();
    world.gravity.set(0, -9.81, 0);
    world.broadphase = new CANNON.NaiveBroadphase();
    world.solver.iterations = 10;
    
    // Material system
    const defaultMaterial = new CANNON.Material('default');
    const defaultContactMaterial = new CANNON.ContactMaterial(
        defaultMaterial, defaultMaterial,
        { friction: 0.3, restitution: 0.7 }
    );
    world.addContactMaterial(defaultContactMaterial);
    
    // Helper function to create physics objects
    function createSphere(radius, position, mass, color, friction, restitution) {
        // Three.js mesh
        const geometry = new THREE.SphereGeometry(radius, 32, 32);
        const material = new THREE.MeshStandardMaterial({ 
            color: color,
            metalness: 0.3,
            roughness: 0.4
        });
        const mesh = new THREE.Mesh(geometry, material);
        mesh.position.set(...position);
        mesh.castShadow = true;
        mesh.receiveShadow = true;
        scene.add(mesh);
        
        // Cannon.js body
        const shape = new CANNON.Sphere(radius);
        const body = new CANNON.Body({
            mass: mass,
            position: new CANNON.Vec3(...position),
            shape: shape,
            material: defaultMaterial
        });
        body.friction = friction;
        body.restitution = restitution;
        world.addBody(body);
        
        return { mesh, body, mass, friction, restitution };
    }
    
    function createBox(width, height, depth, position, mass, color, friction, restitution) {
        // Three.js mesh
        const geometry = new THREE.BoxGeometry(width, height, depth);
        const material = new THREE.MeshStandardMaterial({ 
            color: color,
            metalness: 0.3,
            roughness: 0.4
        });
        const mesh = new THREE.Mesh(geometry, material);
        mesh.position.set(...position);
        mesh.castShadow = true;
        mesh.receiveShadow = true;
        scene.add(mesh);
        
        // Cannon.js body
        const shape = new CANNON.Box(new CANNON.Vec3(width/2, height/2, depth/2));
        const body = new CANNON.Body({
            mass: mass,
            position: new CANNON.Vec3(...position),
            shape: shape,
            material: defaultMaterial
        });
        body.friction = friction;
        body.restitution = restitution;
        world.addBody(body);
        
        return { mesh, body, mass, friction, restitution };
    }
    
function createPlane(position, rotation, color) {
        // Three.js mesh
        const geometry = new THREE.PlaneGeometry(30, 30);
        const material = new THREE.MeshStandardMaterial({ 
            color: color,
            side: THREE.DoubleSide,
            metalness: 0.1,
            roughness: 0.6
        });
        const mesh = new THREE.Mesh(geometry, material);
        mesh.position.set(...position);
        mesh.rotation.x = rotation[0];
        mesh.rotation.y = rotation[1];
        mesh.rotation.z = rotation[2];
        mesh.receiveShadow = true;
        scene.add(mesh);
        
        // Cannon.js body
        const shape = new CANNON.Plane();
        const body = new CANNON.Body({
            mass: 0,
            position: new CANNON.Vec3(...position),
            shape: shape,
            material: defaultMaterial
        });
        body.quaternion.setFromEuler(rotation[0], rotation[1], rotation[2]);
        world.addBody(body);
        
        return { mesh, body };
    }
    
    // === CREATE YOUR EXPERIMENT OBJECTS BELOW ===
    
    // Example: Create objects based on the experiment
    
    // === END EXPERIMENT OBJECTS ===
    
    // Animation loop
    const timeStep = 1 / 60;
    let lastTime = 0;
    
    function animate(time) {
        requestAnimationFrame(animate);
        
        const deltaTime = (time - lastTime) / 1000;
        lastTime = time;
        
        // Step physics world
        world.step(timeStep, deltaTime, 3);
        
        // Sync Three.js meshes with Cannon.js bodies
        objects.forEach(obj => {
            if (obj.mesh && obj.body) {
                obj.mesh.position.copy(obj.body.position);
                obj.mesh.quaternion.copy(obj.body.quaternion);
            }
        });
        
        renderer.render(scene, camera);
    }
    
    // Handle window resize
    window.addEventListener('resize', () => {
        camera.aspect = window.innerWidth / window.innerHeight;
        camera.updateProjectionMatrix();
        renderer.setSize(window.innerWidth, window.innerHeight);
    });
    
    // Start animation
    animate(0);
    
    // Return control functions for dynamic updates
    return {
        getScene: () => scene,
        getCamera: () => camera,
        updateGravity: (x, y, z) => world.gravity.set(x, y, z),
        updateTimeScale: (scale) => { /* Adjust simulation speed */ },
        getObjects: () => objects,
        
        updateObjectParameter: (objectIndex, paramName, value) => {
            const obj = objects[objectIndex];
            if (!obj || !obj.body) return false;
            
            switch(paramName) {
                case 'mass':
                    obj.body.mass = value;
                    obj.body.updateMassProperties();
                    break;
                case 'velocity':
                    obj.body.velocity.set(value[0], value[1], value[2]);
                    break;
                case 'friction':
                    obj.body.friction = value;
                    break;
                case 'restitution':
                    obj.body.restitution = value;
                    break;
                default:
                    return false;
            }
            return true;
        }
    };
})();
```

Constraints:
- Use only Three.js r128+ and cannon-es APIs
- Maximum 10 physics objects per scene
- Include proper error handling
- Make code educational and readable
- Generate COMPLETE, EXECUTABLE code (no placeholders)
- For pendulums, use CANNON.PointToPointConstraint or CANNON.DistanceConstraint
- For springs, use CANNON.Spring

If you cannot understand the experiment description, return an empty objects array with a clear error message in the "errors" field.
"""


class PhysicsAIEngine:
    """
    Physics-specific AI engine using Gemini 3.0 Flash.
    """
    
    def __init__(self, model_name=None):
        self.model_name = model_name or "gemini-2.5-flash"
        self.system_instruction = PHYSICS_SYSTEM_PROMPT
    
    def generate_experiment_code(self, description: str) -> dict:
        """
        Converts natural language to Three.js + physics code.
        
        Args:
            description: Natural language experiment description
            
        Returns:
            dict with keys: title, description, concept, threejs_code, 
                          physics_config, objects, parameters, errors
        """
        try:
            # Create AI engine instance
            engine = KusmusAIEngine(
                system_instruction=self.system_instruction,
                model_name=self.model_name
            )
            
            # Generate response
            response_text, thought_trace = engine.generate_response(
                f"Generate a physics experiment for: {description}"
            )
            
            # Parse JSON from response
            result = self._parse_response(response_text)
            
            if not result.get('threejs_code'):
                result['errors'] = result.get('errors', []) + ["Failed to generate code"]
            
            return result
            
        except Exception as e:
            return {
                "title": "Error",
                "description": description,
                "concept": "Physics",
                "threejs_code": "",
                "physics_config": {},
                "objects": [],
                "parameters": {},
                "errors": [f"AI generation failed: {str(e)}"]
            }
    
    def _parse_response(self, response_text: str) -> dict:
        """
        Parse the AI response and extract JSON.
        """
        try:
            # Look for JSON block in response
            json_pattern = r'```json\s*(\{.*?\})\s*```'
            match = re.search(json_pattern, response_text, flags=re.DOTALL)
            
            if match:
                json_str = match.group(1)
                result = json.loads(json_str)
                
                # Also extract code if in separate block
                code_pattern = r'```javascript\s*(.*?)\s*```'
                code_match = re.search(code_pattern, response_text, flags=re.DOTALL)
                if code_match:
                    result['threejs_code'] = code_match.group(1).strip()
                
                return result
            
            # Try to parse entire response as JSON
            return json.loads(response_text)
            
        except json.JSONDecodeError:
            # If no JSON found, create a basic response
            return {
                "title": "Physics Experiment",
                "description": response_text[:100],
                "concept": "Physics",
                "threejs_code": self._generate_fallback_code(response_text),
                "physics_config": {"gravity": [0, -9.81, 0], "timeScale": 1.0},
                "objects": [],
                "parameters": {},
                "errors": ["Could not parse AI response, using fallback"]
            }
    
    def _generate_fallback_code(self, description: str) -> str:
        """
        Generate a simple fallback visualization.
        """
        return f"""
// Fallback visualization for: {description}
// Please try a more specific description

(function() {{
    const scene = new THREE.Scene();
    scene.background = new THREE.Color(0x1a1a2e);
    
    const camera = new THREE.PerspectiveCamera(60, window.innerWidth / window.innerHeight, 0.1, 1000);
    camera.position.set(0, 5, 10);
    camera.lookAt(0, 0, 0);
    
    const renderer = new THREE.WebGLRenderer({{ antialias: true }});
    renderer.setSize(window.innerWidth, window.innerHeight);
    document.body.appendChild(renderer.domElement);
    
    // Basic lighting
    const ambientLight = new THREE.AmbientLight(0x404040, 0.5);
    scene.add(ambientLight);
    
    const directionalLight = new THREE.DirectionalLight(0xffffff, 1);
    directionalLight.position.set(5, 10, 5);
    scene.add(directionalLight);
    
    // Ground
    const planeGeometry = new THREE.PlaneGeometry(20, 20);
    const planeMaterial = new THREE.MeshStandardMaterial({{ color: 0x444444 }});
    const plane = new THREE.Mesh(planeGeometry, planeMaterial);
    plane.rotation.x = -Math.PI / 2;
    scene.add(plane);
    
    function animate() {{
        requestAnimationFrame(animate);
        renderer.render(scene, camera);
    }}
    animate();
}})();
"""
    
    def generate_with_fallback(self, description: str) -> dict:
        """
        Generate experiment with fallback to 2.5 Flash if 3.0 fails.
        """
        result = self.generate_experiment_code(description)
        
        if result.get('errors') and 'model' in str(result.get('errors', [''])).lower():
            # Try with 2.5 Flash fallback
            self.model_name = "gemini-2.5-flash-lite"
            result = self.generate_experiment_code(description)
            self.model_name = "gemini-3.0-flash-lite"  # Reset
        
        return result
